---
- name: neutron db sync
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
- name: restart neutron server
  service: name=neutron-server state=restarted
- name: apply sysctl
  shell: sysctl -p
- name: pkill dnsmasq
  shell: pkill dnsmasq
- name: restart ovs
  service: name=openvswitch-switch state=restarted
- name: restart neutron plugin openvswitch agent
  service: name=neutron-plugin-openvswitch-agent state=restarted
- name: restart neutron l3 agent
  service: name=neutron-l3-agent state=restarted
- name: restart neutron dhcp agent
  service: name=neutron-dhcp-agent state=restarted
- name: restart neutron metadata agent
  service: name=neutron-metadata-agent state=restarted
- name: activate br-ex
  shell: ifup br-ex
- name: activate eth1
  shell: ifup eth1
- name: restart nova scheduler
  service: name=nova-scheduler state=restarted
