---
- mysql_db: name=neutron state=present
- mysql_user: name=neutron
              password={{ neutron_sql_password }}
              priv=neutron.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_default_ipv4.address }}"
    - "{{ ansible_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1
- keystone_user: >
    user=neutron email=neutron@example.com
    tenant=service
    password={{ keystone_neutron_password }}
    login_user=admin login_tenant_name=admin
    login_password={{ keystone_admin_password }}
- keystone_user: >
    role=admin user=neutron tenant=service
    login_user=admin login_tenant_name=admin
    login_password={{ keystone_admin_password }}
- keystone_service: >
    name=neutron type=network
    description="OpenStack Compute Service"
    public_url="http://{{ ansible_default_ipv4.address }}:9696"
    internal_url="http://{{ ansible_default_ipv4.address }}:9696"
    admin_url="http://{{ ansible_default_ipv4.address }}:9696"
    endpoint="http://{{ ansible_default_ipv4.address }}:35357/v2.0"
    login_user=admin tenant_name=admin
    login_password={{ keystone_admin_password }}
    region=regionOne
- apt: name={{ item }} state=latest
       update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - python-neutronclient
  notify:
  - neutron db sync
  - restart nova api
  - restart nova scheduler
  - restart nova conductor
  - restart neutron server
- template: src=neutron.conf dest=/etc/neutron/neutron.conf
            owner=root group=neutron mode=0640
  notify:
  - restart nova api
  - restart nova scheduler
  - restart nova conductor
  - restart neutron server
- template: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            owner=root group=neutron mode=0644
  notify:
  - restart nova api
  - restart nova scheduler
  - restart nova conductor
  - restart neutron server
- copy: src=empty dest=/etc/neutron/db_sync_flag
        owner=root group=root mode=0400
  notify:
  - neutron db sync
  - restart nova api
  - restart nova scheduler
  - restart nova conductor
  - restart neutron server
- meta: flush_handlers
- copy: src=sysctl.conf dest=/etc/sysctl.conf
        owner=root group=root mode=0644
  notify: apply sysctl
- apt: name={{ item }} state=latest
       update_cache=yes cache_valid_time={{ apt_cache_time }}
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
- template: src=l3_agent.ini dest=/etc/neutron/l3_agent.ini
            owner=root group=neutron mode=0644
  notify:
    - restart neutron plugin openvswitch agent
    - restart neutron dhcp agent
    - restart neutron metadata agent
- template: src=dhcp_agent.ini dest=/etc/neutron/dhcp_agent.ini
            owner=root group=root mode=0644
  notify:
    - restart neutron plugin openvswitch agent
    - restart neutron dhcp agent
    - restart neutron metadata agent
- template: src=dnsmasq-neutron.conf dest=/etc/neutron/dnsmasq-neutron.conf
            owner=root group=root mode=0644
  notify:
    - restart neutron plugin openvswitch agent
    - restart neutron dhcp agent
    - restart neutron metadata agent
  notify: pkill dnsmasq
- template: src=metadata_agent.ini dest=/etc/neutron/metadata_agent.ini
            owner=root group=root mode=0644
  notify: restart ovs
- openvswitch_bridge: bridge=br-ex state=present
  notify:
    - restart neutron plugin openvswitch agent
    - restart neutron dhcp agent
    - restart nova scheduler
    - restart neutron metadata agent
- meta: flush_handlers
- wait_for: port=9696 delay=5
- quantum_network: name=ext-net state=present
                   provider_network_type=flat
                   provider_physical_network=external
                   shared=yes
                   router_external=yes
                   login_username=admin
                   login_password={{ keystone_admin_password }}
                   login_tenant_name=admin
                   region_name=regionOne
- quantum_subnet: name=ext-subnet
                  network_name=ext-net
                  cidr="{{ external_bridge_network }}"
                  enable_dhcp=yes
                  gateway_ip="{{ external_bridge_gateway }}"
                  allocation_pool_start="{{ external_bridge_dhcp_start }}"
                  allocation_pool_end="{{ external_bridge_dhcp_end }}"
                  state=present
                  login_username=admin
                  login_password={{ keystone_admin_password }}
                  login_tenant_name=admin
                  region_name=regionOne
- openvswitch_port: bridge=br-ex port=eth1 state=present
- template: src=interfaces dest=/etc/network/interfaces
            owner=root group=root mode=0644
  notify:
    - activate br-ex
    - activate eth1
