---
- name: ironic db sync
  shell: su -s /bin/sh -c "ironic-dbsync --config-file /etc/ironic/ironic.conf create_schema" ironic
- name: restart ironic api
  service: name=ironic-api state=restarted
- name: restart ironic conductor
  service: name=ironic-conductor state=restarted
- name: install python-pymysql
  shell: su -s /bin/sh -c "dpkg -i /tmp/python-pymysql.deb"
